---
title: "Executive summary"
format: docx
---

Accurate forecasts of ambulance demand are critical inputs when planning and deploying staff and fleet. Such forecasts are required at the national, regional, and sub-regional levels and must take into account the nature of incidents as well as their priorities. Different teams within the organization frequently produce these forecasts independently. As a result, forecasts at various levels may be inconsistent, resulting in conflicting decisions and a lack of coherent coordination in the service. To address this issue, we use forecast reconciliation methods to generate both point and probabilistic forecasts that are coherent and use all available data at all levels of disaggregation.

Implementing and sustaining improvements in EMS necessitate alignments and coordination among various stakeholders, without which teams operate in isolation, leading to conflicts, duplication of work, rework, or work that runs counter to the overall goal of improving service quality. A hierarchical forecasting framework can be used to improve coordination between teams across care services at the national, sub-national, regional, and local levels. Because hierarchical forecasting is based on coherent forecasts, plans at any level can be aligned.

Hierarchical forecasting approaches not only produce consistent forecasts, but they are also more accurate than independent (base) forecasts because they leverage data available throughout the hierarchy.
As a result, the proposed framework in this study can assist EMS managers and professionals in improving forecast accuracy across different levels, as well as improving coordination across the organization.

In summary, the use of forecast reconciliation methods and a hierarchical forecasting framework is crucial for improving coordination and forecast accuracy in emergency medical service, supporting more effective planning and deployment of ambulance staff and resources.
