# Research background {#lit}
Emergency medical services (EMS) are a critical component in the delivery of urgent medical care to communities. An effective service delivery requires accurate resource planning that are generally replying on demand forecasts at operational, tactical and strategic levels.

There is a substantial number of studies on the application of time series forecasting in the Emergency Medical Services. Various areas have been the focus of the literature. Forecasting call volume arrivals is one of the major research topics. @ibrahim2016modeling provide an extensive review of the forecasting models in this context. Another important area is related to forecasting ambulance demand. Although the definition of demand might not be always clearly stated, however, this is typically referring to a situation where a physical resource has been deployed to respond to an incident. This might be also called _attended incidents_. Another demand related variable is verified incidents. These are all incidents that require an action: either send a physical vehicle, deal with via the Clinical Support Desk (e.g. calls), get an external (private) provider to respond to it, or send it through to other channels such as police, firefighters or general practitioners. Our study is aligned with this stream of the literature. Another similar area that is largely studied in the literature, is Emergency Department forecasting. We refer interested readers to @mingliterature2022, @gul2020exhaustive and @wargon2009systematic for extensive reviews of the literature on Emergency Department forecasting. Although crucial to EMS performance, @aringhieri2017emergency state that demand forecasting has received limited research attention in the EMS context. In this section, we provide a brief review of studies on forecasting ambulance demand in EMS.

There are generally two main streams of research related to forecasting ambulance demand in EMS: i) the first stream focuses on the application of time series methods and regression approaches on forecasting aggregate ambulance demand [@vile2012predicting; @sasaki2010using]; ii) the second stream considers forecasting EMS demand in a more finer temporal and geographical granularitties by employing temporal-spatial prediction methods [@zhou2016predicting;@zhou2016predictinglit]. The focus of our study is related to the first stream of research.

@sasaki2010using develop a multivariable regression model to estimate future EMS demands. In addition to the historical demand, the population census for different age groups and counts of the number of companies employing more than five people are included in the regression. The census variables describe groups who may be more likely to need an ambulance. A stepwise ordinary least squares regression analysis with SPSS is used for estimating the parameter and generating forecast. The only performance measure reported in this study is $R^2$. The research design of this study is not rigorous and the study is not reproducible. @vile2012predicting explore using a Singular Spectrum Analysis (SSA) method to generate forecasts of the EMS demand at the national level for 7-day, 14-day, 21-day and 28-day forecast horizons using data provided by the Welsh Ambulance Service Trust (WAST). The performance of this approach is compared with Auto-Regressive Moving Average (ARIMA) and Holt-winter time series methods using Root Mean Squared Error (RMSE). They concluded that point forecasts generated by SSA are more accurate for longer-term, but ARIMA and Holt-winter performance is superior for shorter-term horizons. @vile2016time further develop a decision support system to integrate forecasts generated by SSA. However, the study does not compare and contrast the performance of forecasting methods based on utility measures such as cost, resource utilization or response time. The tool contains options that allow generating forecasts at various levels of granularity, however, it ignore the hierarchical and grouped relationships structure, preventing  aligned decision making and coordination.

@9659837 investigate forecasting EMS demand in a high spatio-temporal resolution of 1×1km spatial regions and 1-hr time intervals using total incidents in Oslo, Norway from January 1st, 2015 up to and including February 11th, 2019. They used multi-layer perceptron (MLP) and long short-term memory (LSTM) models to forecast the EMS demand, and compare them to simple aggregation methods and baselines. The point forecast accuracy is evaluated using Mean Absolute Error (MAE) and Mean Squared Error (MSE) and the forecast distribution is measures by Categorical Cross-Entropy. They shows that while Neural Network models perform better in producing point forecast, a distribution baseline method based on spatial distribution of the incidents across all time steps provide more accurate forecast distribution. @zhou2016predictinglit propose three methods based on Gaussian mixture models, kernel density estimation, and kernel warping to predict 4 weeks into future for a 1-km2 spatial region over an hour. Two years of incidents attended from Toronto, Canada (years 2007 and 2008 with 391,296 events) and Melbourne, Australia (years 2011 and 2012 with  696,975 events) are used to build the model and examine the  performance on test data using mean negative log likelihood. They show that forecasts generated by the proposed methods are significantly more accurate than the current industry practice,  a simple averaging formula. @grekousis2019will investigate the combination of spatial analysis methods with data mining techniques based on  an improved Hungarian algorithm and MLP neural network to identify the most likely locations of future emergency events. The proposed approach is tested using data of 2851 events attended by the EMS in Athens, Greece over 24 weeks. They show that $23.24\%$ of real emergency events lie within 50 meter of the predicted ones and nearly $70\%$ of the real emergency events lie no further away than 150 meter, which is rather accurate given the granularity of the problem at the city level.

We observed a number of limitations in the literature of EMS forecasting, that encourage us to undertake this research. These limitations are summarized as following:

1. Current studies ignore the inherent hierarchical and/or grouped structure of the time series data and the relationship between series at different levels of hierarchy. This may result in incoherent forecasts leading to misaligned planning and decision making. While the hierarchical forecasting methodology has been developed and applied in various domains over the past 10 years [@panagiotelis2022probabilistic], it has never been explored in this area.

2. Current research is mainly concerned with generating point forecast at a single level of hierarchy. There is a lack of studies presenting the entire forecast distribution of daily ambulance demand for the entire hierarchy to inform the whole decision-making process and to better represent the uncertainty of future demand, providing a risk management tool for planners.

3. Reproducibility is still a major challenge in EMS forecasting, as it is unlikely to reproduce the results without the help of the authors of those papers.

4. Another limitation is related to the generated forecasts that are not integer counts. Since actual ambulance counts cannot be negative or fractions, ambulance demand forecasts should be the same. While this might not be an issue when producing forecasts at a single level, producing non-negative count forecasts in a hierarchical/grouped structure is challenging and requires further investigation in the future.

This paper concerns the problem of hierarchical forecasting in EMS and generates and evaluates both point and probabilistic forecast across different levels of the hierarchy, hence addressing some important gaps identified in the literature.
