---
author:
  - name: Bahman Rostami Tabar & Rob&nbsp;J.&nbsp;Hyndman
    affiliation:
      - name: Bahman Rostami-Tabar
        department: Cardiff Business School
        address: 3, Colum Drive
        city: Cardiff
        country: United Kingdom
        postal-code: CF10 3EU
address:
  - Prof. Ming-Hui Huang
  - Editor-in-Chief
  -  Journal of Service Research
subject: Paper submission for peer review
opening: "Dear Prof. Huang,"
closing: "Yours sincerely"
format: letter-pdf
---

We would be grateful if you could consider for publication our manuscript entitled _Hierarchical Time Series Forecasting in Emergency Medical Services_ as an Original Research article in the Journal of Service Research.

Time series forecasting problems at Emergency Medical Services have often inherent hierarchical and grouped structures. For example, the ambulance demand (e.g. arrival calls, verified incidents, attended incidents) in the country could be disaggregated by region, then within each region by health board, within each health board, by station/hospital, and so on down to the postcode area. Demand could also be disaggrgated by other attributes such as priority (e.g Red, Amber, Green) or the nature of incidents. Despite the popularity of such data structure in EMS, the common practice is to produce point forecasts for each time series independently and ignore the structure. This practice may lead to a lack of coordination and possibly undesirable and conflicting outcomes. Practices also rely on point forecasts, which do not acknowledge forecast uncertainty.

In this paper, we aim at filling these gaps identified in the academic literature and practice. We produce probabilistic forecasts of daily incidents attended up to 84 days ahead using hierarchical forecasting methods for using state of the art forecasting methods. We apply hierarchical forecasting methods to produce a probabilistic and coherent forecast of attended incidents at multiple levels of aggregation. We use Exponential Smoothing State Space models, Poisson regression models based on General Linear Models and serial dependencies, a Naive empirical distribution, and an ensemble model to generate base forecasts. These forecasting models collectively account for i) the spline trend, ii) multiple seasonalities, iii) holiday effects, and  iv) serial dependencies in the time series. Our study is fully reproducible and we provide the R code through a Github repository enabling reproduction and refinement of the proposed approach and benchmarks. The proposed approach could also be generalized to forecast requirements in other healthcare services, such as admissions in Emergency Department, or call volumes in clinical desk services. 

Thank you very much for your consideration of this manuscript. We are looking forward to hearing from you in due course.
